razopy/razopy/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin-panel/', admin.site.urls),
    path('', include('users.urls')),
    path('accounts/', include('accounts.urls')),
    path('admins/', include('admins.urls')),
    path('registrations/', include('registrations.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

razopy/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name='home'),
    path('items/',views.items, name='items'),
    path('token-bidding/',views.token_bidding, name='token_bidding'),
    path('categories/',views.categories, name='categories'),
    path('categories/<str:category>/', views.categories, name='categories'),
    path('notice/',views.notice, name='notice'),
    path('profile/',views.profile, name='profile'),
    path('edit-profile/',views.edit_profile, name='edit_profile'),
    path('profile-created/',views.profile_created, name='profile_created'),
    path('wallet/', views.wallet, name='wallet'),
    path('add_funds/', views.add_funds, name='add_funds'),
    path('payment_success/', views.payment_success, name='payment_success'),
    path('wallet/redeem/', views.redeem, name='redeem'),
    path('remove-profile/<int:user_id>',views.remove_profile, name='remove_profile'),
    path('cart/',views.cart, name='cart'),
    path('addtocart/<int:id>',views.addtocart, name='addtocart'),
    path('remove-item/<int:id>', views.remove_item, name="remove_item"),
    path('sell/<int:id>', views.sell, name='sell'),
    path('cancel-sale/<int:id>', views.cancel_sale, name='cancel_sale'),
    path('edit-token/<int:id>', views.edit_token, name='edit_token'),
    path('checkout/',views.checkout, name='checkout'),
    path('checkout-single/<int:id>',views.checkout_single, name='checkout_single'),
    path('create/',views.create, name='create'),
    path('single-item/<int:id>', views.single_item, name='single_item'),
    path('like/<int:id>',views.like, name='like'),
    path('dislike/<int:id>',views.dislike, name='dislike'),
    path('base/',views.base, name='base'),
    path('complete_transaction/<int:id>',views.complete_transaction, name='complete_transaction'),
    path('checkout_complete_transaction/',views.checkout_complete_transaction, name='checkout_complete_transaction'),
]

razopy/users/models.py
from django.apps import apps
from django.db import models
from django.contrib.postgres.fields import ArrayField

def get_account_model():
    return apps.get_model('admins', 'Category')

def get_account_model():
    return apps.get_model('accounts', 'Account')


class Token(models.Model):
    name = models.CharField(max_length=200, null=True)
    description = models.TextField()
    price = models.FloatField()
    brand = models.CharField(max_length=100, null=True)
    image = models.ImageField(null=True, blank=True)
    likes_count = models.FloatField(default=0)
    category = models.ForeignKey('admins.Category', on_delete=models.CASCADE, null=True)
    owner = models.ForeignKey('accounts.Account', on_delete=models.CASCADE)
    author = models.ForeignKey('accounts.Account', on_delete=models.CASCADE, related_name='token_author', null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    

class Like(models.Model):
    owner = models.ForeignKey('accounts.Account', on_delete=models.CASCADE)
    token = models.ForeignKey(Token, on_delete=models.CASCADE, related_name='likes')
    likes = models.BooleanField(default=False)
    

class Cart(models.Model):
    cart_owner = models.ForeignKey('accounts.Account', on_delete=models.SET_NULL, blank=True, null=True)
    submitted = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    total_price = models.FloatField(default=0)

    def __str__(self):
        return str(self.id)
    

class CartItems(models.Model):
    cart_items = models.ForeignKey(Token, on_delete=models.SET_NULL, blank=True, null=True, related_name='cart_items')
    account = models.ForeignKey('accounts.Account', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return str(self.id)



class Payments(models.Model):
    amount = models.FloatField(blank=True, null=True)
    sold = models.BooleanField(default=False, null=True, blank=False)
    method = models.CharField(max_length=200, default='Razorpay')
    timestamp = models.DateTimeField(auto_now_add=True)
    razor_pay_payment_id = models.CharField(max_length=100, null=True, blank=True)
    razor_pay_order_id = models.CharField(max_length=100, null=True, blank=True)
    razor_pay_signature = models.CharField(max_length=100, null=True, blank=True)
    customer = models.ForeignKey('accounts.Account', on_delete=models.SET_NULL,  blank=True, null=True)

    def __str__(self):
        return str(self.id)



class Wallet(models.Model):
    user = models.OneToOneField('accounts.Account', on_delete=models.CASCADE, related_name='wallet_obj')
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    transaction_history = ArrayField(models.CharField(max_length=100), default=list)
    razor_pay_payment_id = models.CharField(max_length=100, null=True, blank=True)
    razor_pay_order_id = models.CharField(max_length=100, null=True, blank=True)
    razor_pay_signature = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return str(self.id)

razopy/templates/admins_temp/admin-banner-edit.html
{% extends 'admins_temp/admin-base.html' %}

{% block title %} Razopy-Edit Banners {% endblock %}

{% block content %}
    <div class="main-panel">
        <div class="content-wrapper">
            <h3 class="card-title text-center mt-5">Edit Banner</h3>
            <div class="row" style="width: 94%; margin-left: 3%">
                <div class="col-12 grid-margin">
                    <div class="card mt-5">
                        <div class="card-body mt-3 mb-3">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                                <a href="{% url 'news' %}" class="btn btn-light">Cancel</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
    </div>
{% endblock %}

razopy/templates/admins_temp/admin-base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Razopy-Admin-Base{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'vendors/mdi/css/materialdesignicons.min.css' %} ">
    <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %} ">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="{% static 'vendors/jvectormap/jquery-jvectormap.css' %} ">
    <link rel="stylesheet" href="{% static 'vendors/flag-icon-css/css/flag-icon.min.css' %} ">
    <link rel="stylesheet" href="{% static 'vendors/owl-carousel-2/owl.carousel.min.css' %} ">
    <link rel="stylesheet" href="{% static 'vendors/owl-carousel-2/owl.theme.default.min.css' %} ">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static 'css/style.css' %} ">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %} ">
  </head>
  <body>
    <div class="container-scroller">
      <!-- partial:partials/_sidebar.html -->
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
          <a class="sidebar-brand brand-logo" href="{% url 'admin_home' %}"><img src="{% static 'img/razopay.png' %} " alt="logo" /></a>
          <a class="sidebar-brand brand-logo-mini" href="index.html"><img src="{% static 'img/logo-mini.svg' %} " alt="logo" /></a>
        </div>
        <ul class="nav" style="position: fixed">
          <li class="nav-item profile" id="admin-home">
            <div class="profile-desc">
              <div class="profile-pic">
                <div class="count-indicator">
                  <img class="img-xs " src="{% static 'img/logo-ct.png' %} " alt="">
                </div>
                <div class="profile-name">
                  <h5 class="mb-0 font-weight-bold text-light">Admin</h5>
                  <span class="text-light">Admin Dashboard</span>
                </div>
              </div>
          </li>
          <li class="nav-item nav-category">
            <span class="nav-link text-light mt-3">Navigation</span>
          </li>
          <li class="nav-item menu-items" id="admin_home">
            <a class="nav-link" href="{% url 'admin_home' %}">
              <span class="menu-icon">
                <i class="mdi mdi-speedometer"></i>
              </span>
              <span class="menu-title text-light">Dashboard</span>
            </a>
          </li>
          <li class="nav-item menu-items" id="admin_items">
            <a class="nav-link" href="{% url 'admin_items' %}">
              <span class="menu-icon">
                <i class="mdi mdi-speedometer"></i>
              </span>
              <span class="menu-title text-light">Items</span>
            </a>
          </li>
          <li class="nav-item menu-items" id="admin_user_control">
            <a class="nav-link" href="{% url 'admin_user_control' %}">
              <span class="menu-icon">
                <i class="mdi mdi-table-large"></i>
              </span>
              <span class="menu-title text-light">User Cotrol</span>
            </a>
          </li>
          <li class="nav-item menu-items" id="admin_wallet">
            <a class="nav-link" href="{% url 'admin_wallet' %}">
              <span class="menu-icon">
                <i class="mdi mdi-chart-bar"></i>
              </span>
              <span class="menu-title text-light">Wallet</span>
            </a>
          </li>
          <li class="nav-item nav-category">
            <span class="nav-link text-light mt-5">Accounts</span>
          </li>

            {% if request.user.is_authenticated %}

                <li class="nav-item menu-items">
                    <a class="nav-link" href="{% url 'admin_logout' %}">
                    <span class="menu-icon">
                        <i class="mdi mdi-file-document-box"></i>
                    </span>
                    <span class="menu-title text-light">Logout</span>
                    </a>
                </li>
              
            {% endif %}

        </ul>
      </nav>
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar p-0 fixed-top d-flex flex-row">
          <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
            <a class="navbar-brand brand-logo-mini" href="index.html"><img src="{% static 'img/logo-mini.svg' %} " alt="logo" /></a>
          </div>
          <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
            <ul class="navbar-nav w-100">
              <li class="nav-item w-100">
                <form class="nav-link mt-2 mt-md-0 d-none d-lg-flex search" method="GET" action="{% url 'admin_items' %}">
                  <input type="text" name="q" class="form-control text-white w-50" placeholder="Search tokens">
                  <button type="submit" class="btn btn-outline-primary mx-3 mt-1" style="height: 30px; border-radius: 8px;">Search</button>
                </form>
              </li>
            </ul>
            <ul class="navbar-nav navbar-nav-right">
              <li class="nav-item dropdown d-none d-lg-block">
                <a class="nav-link btn btn-primary create-new-button" id="createbuttonDropdown" href="{% url 'create' %}">Create Token</a>
              </li>
              <li class="nav-item dropdown d-none d-lg-block">
                <a class="nav-link btn btn-primary create-new-button" id="createbuttonDropdown" href="{% url 'category' %}">Category</a>
              </li>
              <li class="nav-item dropdown d-none d-lg-block">
                <a class="nav-link btn btn-primary create-new-button" id="createbuttonDropdown" href="{% url 'news' %}">Banner/News</a>
              </li>
            </ul>
            <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
              <span class="mdi mdi-format-line-spacing"></span>
            </button>
          </div>
        </nav>
        <!-- partial -->
          <!--content-wrapper -->  

          {% block content %}

          {% endblock %}

          <!-- content-wrapper ends -->
          <!-- partial:partials/_footer.html -->
          <footer class="footer">
            <div class="d-sm-flex justify-content-center justify-content-sm-between">
              <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com 2021</span>
              <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin template</a> from Bootstrapdash.com</span>
            </div>
          </footer>
          <!-- partial -->
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="{% static 'vendors/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'vendors/progressbar.js/progressbar.min.js' %}"></script>
    <script src="{% static 'vendors/jvectormap/jquery-jvectormap.min.js' %}"></script>
    <script src="{% static 'vendors/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
    <script src="{% static 'vendors/owl-carousel-2/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}" type="text/javascript"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'js/off-canvas.js' %}"></script>
    <script src="{% static 'js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'js/misc.js' %}"></script>
    <script src="{% static 'js/settings.js' %}"></script>
    <script src="{% static 'js/todolist.js' %}"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="{% static 'js/dashboard.js' %}"></script>
    <!-- End custom js for this page -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

razopy/templates/admins_temp/admin-category.html
{% extends 'admins_temp/admin-base.html' %}

{% load static %}

{% block title %} Razopy-Category-Management {% endblock %}

{% block content %}

<div class="main-panel">
    <div class="content-wrapper">
        <h3 class="card-title text-center mt-5">Category management</h3>
        <div class="card-body">
            <form class="d-flex flex-column w-50 mx-auto mt-2" action="{% url 'category' %}" method="POST">
                {% csrf_token %}
                {{form.name}}
                <input type="submit" value="Create" class="mb-5 text-white btn bg-primary bg-gradient w-25 mt-4">
            </form>
          </div>

        <div class="row" style="width: 94%; margin-left: 3%">
        <div class="col-12 grid-margin">
            <div class="card">
            <div class="card-body">
                <div class="table-responsive" style="background: black; width: 80%; margin-left: 12%; border-radius: 20px">
                <table class="table" style="text-align: center">
                    <thead>
                    <tr>
                        <th> id</th>
                        <th> Category Name </th>
                        <th> Edit </th>
                        <th> List/Unlist </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for i in data %}
                        <tr>
                        <td><span class="ps-2"> {{i.id}} </span></td>
                        <td> {{i.name}} </td>
                        <td><a class="btn btn-outline-primary" href="{% url 'edit' i.id %}">Edit</a></a></td>
                        <td>
                            {% if i.is_active%}
                                <a class="btn btn-outline-danger mx-2" href="{% url 'unlist' i.id %}" onclick="return confirm('Unlist this category?')">Unlist</a>
                            {% else %}
                                <a class="btn btn-outline-success" href="{% url 'list' i.id %}" onclick="return confirm('List your category?')">List</a>
                            {% endif %}
                        </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

razopy/templates/admins_temp/admin-home.html
{% extends 'admins_temp/admin-base.html' %}

{% load static %}

{% block title %} Razopy-Admin-Home {% endblock %}

{% block content %}

<div class="main-panel">
    <div class="content-wrapper">
      <div class="row">
        <div class="col-xl-6 col-sm-6 grid-margin stretch-card mt-5">
          <div class="card" style="border-radius: 40px;">
            <div class="container col-xl-12 col-sm-12" style="position: absolute; width: 100%; margin-top: 2rem; font-size: 1.7vw;">
              <h2>Creativity Produce Quality!</h2>
              <p>Digital marketplace for digital art collections</p>
              <a href="{% url 'admin_items' %}" class="btn btn-danger btn-lg" style="margin-right: 1rem; font-weight: bold">Explore</a>
              <a href="{% url 'create' %}" class="btn btn-primary btn-lg" style="font-weight: bold">Create</a>
            </div>
            <img src="{% static 'img/admin-home1.jpeg' %}" style="border-radius: 40px">
          </div>
        </div>
        <div class="col-xl-6 col-sm-6 grid-margin stretch-card mt-5">
          <div class="card" style="border-radius: 40px;  background: #3b3c51;">
              <div class="container col-xl-12 col-sm-12" style="position: absolute; width: 100%; margin-top: 2rem; font-size: 1.7vw; text-align: end;">
                <h2>Amazing Growth!</h2>
                <p>Explore through your digital wallet</p>
                <a href="{% url 'admin_items' %}" class="btn btn-danger btn-lg" style="margin-right: 1rem; font-weight: bold">Explore</a>
                <a href="{% url 'admin_wallet' %}" class="btn btn-primary btn-lg" style="font-weight: bold">Wallet</a>
              </div>
              <img src="{% static 'img/admin-home2.jpg' %}" style="border-radius: 40px; width:56%; ">
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Admin's profile</h4>
              <img src="{{user.profile_pic.url}}"
                alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2 mx-4"
                style="width: 150px; z-index: 1">
                <div>
                  <a href="{% url 'edit_profile' %}" class="btn btn-primary mx-2" data-mdb-ripple-color="dark" style="z-index: 1;">Edit profile</a>
                  <a href="{% url 'admin_wallet' %}" class="btn btn-primary" data-mdb-ripple-color="dark" style="z-index: 1;">Wallet</a>
                </div>
              <div class="bg-gray-dark d-flex d-md-block d-xl-flex flex-row py-3 px-4 px-md-3 px-xl-4 rounded mt-3">
                <div class="text-md-center text-xl-left">
                  <h5 class="mx-3">Brand: </h5>
                </div>
                <div class="text-md-center text-xl-left">
                  <h5 class="mb-0">{{user.username}}</h5>
                </div>
              </div>
              <div class="bg-gray-dark d-flex d-md-block d-xl-flex flex-row py-1 px-4 px-md-3 px-xl-4 rounded mt-1">
                <div class="text-md-center text-xl-left">
                  <h5 class="mx-3">Email: </h5>
                </div>
                <div class="text-md-center text-xl-left">
                  <h5 class="mb-0">{{user.email}}</h5>
                </div>
              </div>
              <div class="bg-gray-dark d-flex d-md-block d-xl-flex flex-row py-1 px-4 px-md-3 px-xl-4 rounded mt-3">
                <div class="text-md-center text-xl-left">
                  <h5 class="mx-3">Phone: </h5>
                </div>
                <div class="text-md-center text-xl-left">
                  <h5 class="mb-0">{{user.phone}}</h5>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-sm-4 grid-margin">
          <div class="card">
            <div class="card-body">
              <h5>Sales</h5>
              <div class="row">
                <div class="col-8 col-sm-12 col-xl-8 my-auto">
                  <div class="d-flex d-sm-block d-md-flex align-items-center">
                    <h2 class="mb-0">₹{{ sales_profit }}</h2>
                    <p class="text-success ms-2 mb-0 font-weight-medium">+3.5%</p>
                  </div>
                  <h6 class="text-muted font-weight-normal"> 3.5% of the sales will be commission</h6>
                </div>
                <div class="col-4 col-sm-12 col-xl-4 text-center text-xl-right">
                  <i class="icon-lg mdi mdi-biohazard text-success ms-auto"></i>
                </div>
              </div>
              <br><br>
              <h5 class="mt-5">Purchase</h5>
              <div class="row">
                <div class="col-8 col-sm-12 col-xl-8 my-auto">
                  <div class="d-flex d-sm-block d-md-flex align-items-center">
                    <h2 class="mb-0">₹{{ purchase_amount }}</h2>
                    <p class="text-danger ms-2 mb-0 font-weight-medium">-3.5% </p>
                  </div>
                  <h6 class="text-muted font-weight-normal">3.5% of that will be added into the commission.</h6>
                </div>
                <div class="col-4 col-sm-12 col-xl-4 text-center text-xl-right">
                  <i class="icon-lg mdi mdi-wallet-travel text-danger ms-auto"></i>
                </div>
              </div>
              <div class="text-center">
                <h6 class="text-muted font-weight-normal mt-5">more details in Admin's wallet</h6>
                <a href="{% url 'admin_wallet' %}" class="btn btn-info">View</a>
              </div>
            </div>
          </div>
        </div>

        <div class="col-sm-4 grid-margin">
          <div class="card">
            <div class="card-body">
              <h5>Tokens</h5>
              <div class="row">
                <div class="col-8 col-sm-12 col-xl-8 my-auto">
                  <div class="d-flex d-sm-block d-md-flex align-items-center">
                    <h2 class="mb-0">{{ total_tokens }}</h2>
                  </div>
                  <h6 class="text-muted font-weight-normal">tokens in the marketplace</h6>
                </div>
                <div class="col-4 col-sm-12 col-xl-4 text-center text-xl-right">
                  <i class="icon-lg mdi mdi-calendar-multiple-check text-danger ms-auto"></i>
                </div>
              </div>
              <br><br>
              <h5 class="mt-5">Users</h5>
              <div class="row">
                <div class="col-8 col-sm-12 col-xl-8 my-auto">
                  <div class="d-flex d-sm-block d-md-flex align-items-center">
                    <h2 class="mb-0">{{ total_users }}</h2>
                  </div>
                  <h6 class="text-muted font-weight-normal">User accounts available in<br> the marketplace</h6>
                </div>
                <div class="col-4 col-sm-12 col-xl-4 text-center text-xl-right">
                  <i class="icon-lg mdi mdi-account-multiple text-success ms-auto"></i>
                </div>
              </div>
              <div class="text-center">
                <h6 class="text-muted font-weight-normal mt-5">more details in User controls</h6>
                <a href="{% url 'admin_user_control' %}" class="btn btn-info">View</a>
              </div>
            </div>
          </div>
        </div>
        
        <div class="col-md-4 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Transaction Details</h4>
              <div>
                <canvas id="myChart" style="margin-top: 100px; height: 400px;"></canvas>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-8 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <div class="d-flex flex-row justify-content-between">
                <h4 class="card-title mb-1">Token details</h4>
              </div>
              <div style="height: 400px;">
                <canvas id="myChart2" style="margin-left: 30%"></canvas>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <div class="row ">
        <div class="col-12 grid-margin">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Sales Report</h4>
              <div class="table-responsive">
                  <table class="table">
                      <thead>
                          <tr>
                              <th class="text-light">Type</th>
                              <th class="text-light">Description</th>
                              <th class="text-light">Amount</th>
                          </tr>
                      </thead>
                      <tbody>
                          {% for row in rows %}
                          <tr>
                              <td>{{ row.type }}</td>
                              <td>{{ row.description }}</td>
                              <td>{{ row.amount }}</td>
                          </tr>
                          {% endfor %}
                      </tbody>
                  </table>
              </div>
            </div>                    
          </div>
        </div>
      </div>
    </div>

  
<script>
  var mylink=document.getElementById("admin_home")
  mylink.classList.add("active")
</script>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
  const ctx = document.getElementById('myChart');

  new Chart(ctx, {
    type: 'bar',
    data: {
      labels: ['Sales', 'Commission', 'Profit', 'Balance', 'Purchase'],
      datasets: [{
        label: 'Admin Dashboard',
        data: [
          {{ sales_profit }},
          {{ commission_profit }},
          {{ commission_and_sales_profit }},
          {{ balance }},
          {{ purchase_amount }}
        ],
        borderWidth: 1
      }]
    },
    options: {
      scales: {
        y: {
          beginAtZero: true
        }
      }
    }
  });
</script>

<script>
  // Define configuration for the polar area chart
  var config2 = {
    type: 'polarArea',
    data: {
      datasets: [{
        label: 'Token Count by Category',
        backgroundColor: [
          'rgba(255, 99, 132, 0.2)',
          'rgba(54, 162, 235, 0.2)',
          'rgba(255, 206, 86, 0.2)',
          'rgba(75, 192, 192, 0.2)',
          'rgba(153, 102, 255, 0.2)',
          'rgba(255, 159, 64, 0.2)'
        ],
        borderColor: [
          'rgba(255,99,132,1)',
          'rgba(54, 162, 235, 1)',
          'rgba(255, 206, 86, 1)',
          'rgba(75, 192, 192, 1)',
          'rgba(153, 102, 255, 1)',
          'rgba(255, 159, 64, 1)'
        ],
        borderWidth: 1,
        data: [
          {% for category in categories %}
            {{ category.token_set.count }},
          {% endfor %}
        ]
      }]
    },
    options: {
      responsive: true,
      legend: {
        position: 'top',
      },
      title: {
        display: true,
        text: 'Token Count by Category'
      }
    }
  };

  // Instantiate the polar area chart
  var ctx2 = document.getElementById('myChart2').getContext('2d');
  var myChart2 = new Chart(ctx2, config2);
</script>



{% endblock%}

razopy/templates/admins_temp/admin-news-edit.html
{% extends 'admins_temp/admin-base.html' %}

{% block title %} Razopy-Edit News {% endblock %}

{% block content %}
    <div class="main-panel">
        <div class="content-wrapper">
            <h3 class="card-title text-center mt-5">Edit News</h3>
            <div class="row" style="width: 94%; margin-left: 3%">
                <div class="col-12 grid-margin">
                    <div class="card mt-5">
                        <div class="card-body mt-3 mb-3">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                                <a href="{% url 'news' %}" class="btn btn-light">Cancel</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
    </div>
{% endblock %}